package main

import (
	_ "github.com/yasar-arafat/go-project-starter/docs" // docs is generated by Swag CLI, you have to import it.
	"github.com/yasar-arafat/go-project-starter/server"
)

// @title Swagger Example API
// @version 1.0
// @description ProjectStarter API
// @title ProjectStarter API

// @host 127.0.0.1:8585
// @BasePath /api

// @schemes http
// @produce	application/json
// @consumes application/json

func main() {
	server.Run()
}
